<?xml version="1.0" encoding="utf-8"?><Database Name="BazaMagazyn" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\BazaMagazyn.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BazaMagazynConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Category" Member="CategoryModels">
    <Type Name="CategoryModel">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="Category_Product" Member="ProductModels" ThisKey="ID" OtherKey="Category" Type="ProductModel" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="ProductModels">
    <Type Name="ProductModel">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Category" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_File" Member="FileModels" ThisKey="ID" OtherKey="ProductID" Type="FileModel" />
      <Association Name="Category_Product" Member="CategoryModel" ThisKey="Category" OtherKey="ID" Type="CategoryModel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Files" Member="FileModels">
    <Type Name="FileModel">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="ContentType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_File" Member="ProductModel" ThisKey="ProductID" OtherKey="ID" Type="ProductModel" IsForeignKey="true" />
    </Type>
  </Table>
</Database>